### ISSUE TITLE
Rota de signup

### ISSUE THREAD

**Issue by tysm** [fisufba/fisufba-server#7]

**Comment by thelink2012** [comment]
Lembrando que um usuário não pode se cadastrar diretamente. Ele precisa pedir há um usuário de hierarquia superior (i.e. admin cadastra atendente e fisio, e atendente cadastra paciente).

Provavelmente fica interessante como uma rota de POST em accounts.

**Comment by tysm** [comment]
ficou um post em /accounts/signup

**Comment by tysm** [comment]
/accounts ficou sem uso então será removida

**Comment by thelink2012** [comment]
Closed as duplicate
