### ISSUE TITLE
Rota de signdown

### ISSUE THREAD

**Issue by tysm** [fisufba/fisufba-server#8]

**Comment by thelink2012** [comment]
@helwohs eu ainda não entendi esse signdown. Isso é pra descadastrar? Acho desnecessário.

**Comment by tysm** [comment]
Mas e se o usuário quiser descartar a conta? Não é tão difícil, basicamente basta verificar se o usuário está autenticado e fazer uma query no banco.

**Comment by thelink2012** [comment]
É dificil porque o que acontece quando o usuário decide fazer o seguinte no mesmo CPF: signin => signdown => signin? Esse é um caso "complexo" que esse tipo de feature introduz.

**Comment by tysm** [comment]
Faz sentido.
